name: Publish UnoWeb

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4


    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.102
    - name: Setup Project
      run: |
       wget -O "AppName.zip" "${{ secrets.PROJECTURL }}"
       brew install sevenzip
       7z x "AppName.zip"
    - name: Setup Uno
      run: |
            dotnet tool install -g uno.check
            uno-check -v --ci --non-interactive  --skip xcode --skip androidemulator --skip androidsdk --skip dotnetworkloads-9.0.101 --skip git --skip dotnetnewunotemplates --skip openjdk   --target wasm --fix

    - name: Publish App
      run: |
         dotnet publish -f net9.0-browserwasm -c Release -o ./publish

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./publish/wwwroot
    
